### Authenticate user
POST http://localhost:8080/api/authenticate?username=user&password=password

### Public API
GET http://localhost:8080/api/public

### Private API
GET http://localhost:8080/api/private
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzZWN1cmUtYXBpIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6InVzZXIiLCJleHAiOjE1NjE2MzU2NjksInJvbCI6WyJST0xFX1VTRVIiXX0.EFWmiHLygYJTvMKbCCTqPpRsPcOQLsS4h3HGOt6vuG5tkQM1zHFUXJy77Y_OQNeLUHCEEfxIMwcGHbXmlZx6mA

###
